### PR TITLE
added source linking

### LINKED ISSUE #480: Consider adding source linking
With source linking it will be possible to debug in edge case scenarios.

I have a scenario where I'm ending up [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/impl/TcpClientAdapter.cs#L33) but calling this directly:

```
var adds = await Dns.GetHostAddressesAsync(host).ConfigureAwait(false);
var ep = TcpClientAdapterHelper.GetMatchingHost(adds, AddressFamily.InterNetwork);
```

yields an `IpAddress`.

### PR DESCRIPTION
**Pull request by paulomorgado**
## Proposed Changes

With source linking it will be possible for users of the NuGet package to debug in edge case scenarios.

Fixes #480 

## Types of Changes

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

I don't think this would be a breaking change for the next minor version.

### CODE REVIEW

**Comment by paulomorgado** [comment]
Can anyone see why the build is failing in concourse? I can't see the results.

**Comment by kjnilsson** [comment]
something like 

```CSC : error CS0016: Could not write to output file '/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/obj/Debug/netstandard2.0/RabbitMQ.Client.sourcelink.json' -- 'Could not find file "/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/obj/Debug/netstandard2.0/RabbitMQ.Client.sourcelink.json".' [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]```

I will see if we can open access to the PR build

**Comment by paulomorgado** [comment]
But seems to not be a problem in appveyor.

**Comment by paulomorgado** [comment]
Can we add full binary logging to help diagnose cases like this?

http://msbuildlog.com/
https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild#save-a-binary-log

**Comment by bording** [comment]
What version of the .NET Core SDK is the Concourse CI using? It might need to be updated: https://github.com/dotnet/sourcelink#prerequisites

**Comment by kjnilsson** [comment]
It should be 2.0 - I could try updating to 2.1

**Comment by paulomorgado** [comment]
That might work.

**Comment by kjnilsson** [comment]
Having some "technical difficulties" getting our ci image updated with 2.1 which is blocking the merge of this. Will take a look again when I'm back next week.

**Comment by kjnilsson** [comment]
I tried this on my local machine with dotnet 2.1.403 and still get:
```CSC : error CS0016: Could not write to output file '/Users/knilsson/code/rabbitmq/rabbitmq-public-umbrella-master/deps/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/obj/Debug/net451/RabbitMQ.Client.sourcelink.json' -- 'Could not find file "/Users/knilsson/code/rabbitmq/rabbitmq-public-umbrella-master/deps/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/obj/Debug/net451/RabbitMQ.Client.sourcelink.json".' [/Users/knilsson/code/rabbitmq/rabbitmq-public-umbrella-master/deps/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]```

Updated ci to 2.1 as well and it doesn't pass their either. Is source linking something that only works on windows?

**Comment by paulomorgado** [comment]
Let me check that.

**Comment by bording** [comment]
> Updated ci to 2.1 as well and it doesn't pass their either. Is source linking something that only works on windows?

It should work on on other OSes as well. What OS are you trying it on?

**Comment by kjnilsson** [comment]
I use OSX, ci uses Debian stretch atm.

**Comment by paulomorgado** [comment]
@kjnilsson, is it possible to run a build with `/bl:ProjectImports=Embed` and get the msbuild.binlog file?

**Comment by kjnilsson** [comment]
After updating the ci image to 2.1._403_ I re-triggered the build for this PR and get the following errors:

```
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018: The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly. [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018: System.BadImageFormatException: Method has no body [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018: File name: 'LibGit2Sharp' [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018:   at LibGit2Sharp.Core.Proxy.git_buf_free (LibGit2Sharp.Core.Handles.GitBuf buf) [0x00000] in <06ab184b4ccd4259a7a7af2756f77645>:0  [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018:   at LibGit2Sharp.Core.Handles.GitBuf.Dispose () [0x00000] in <06ab184b4ccd4259a7a7af2756f77645>:0  [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018:   at LibGit2Sharp.Core.Proxy.ConvertPath (System.Func`2[T,TResult] pathRetriever) [0x0002e] in <06ab184b4ccd4259a7a7af2756f77645>:0  [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018:   at LibGit2Sharp.Core.Proxy.git_repository_discover (LibGit2Sharp.Core.FilePath start_path) [0x00005] in <06ab184b4ccd4259a7a7af2756f77645>:0  [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018:   at LibGit2Sharp.Repository.Discover (System.String startingPath) [0x00006] in <06ab184b4ccd4259a7a7af2756f77645>:0  [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018:   at Microsoft.Build.Tasks.Git.GitOperations.LocateRepository (System.String directory) [0x00000] in <859aea960c5c4805ad7e678061631919>:0  [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018:   at Microsoft.Build.Tasks.Git.RepositoryTasks.LocateRepository (Microsoft.Build.Tasks.Git.LocateRepository task) [0x00007] in <859aea960c5c4805ad7e678061631919>:0  [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018:   at Microsoft.Build.Tasks.Git.LocateRepository.Execute () [0x00038] in <77223f90773a4c0e88a42a7f38595356>:0  [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in <63bca7756d124ea392a81ca1b2d26b9c>:0  [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(20,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x001f6] in <63bca7756d124ea392a81ca1b2d26b9c>:0  [/tmp/build/b95f7b06/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]

```

**Comment by kjnilsson** [comment]
@bording that particular script runs `./build.sh` which uses the `msbuild` that ships with mono yes. `dotnet msbuild` doesn't work so we have to to multi target.

**Comment by paulomorgado** [comment]
Isn't Mono's `msbuild` now Microsoft's `msbuild`?

**Comment by bording** [comment]
@paulomorgado The issue isn't the version of MSBuild, it's the fact that it's running on the mono CLR that is causing a problem in some way.

@kjnilsson I don't know the exact time frame yet, but eventually `dotnet build` will be able to build the .NET Framework targets as well on Linux. They are adding targeting packs that the tooling can pull in to make it work.

**Comment by kjnilsson** [comment]
By that time we may have already dropped the net451 target. :)

**Comment by bording** [comment]
> By that time we may have already dropped the net451 target. :)

Yeah, knowing something's coming in the future definitely doesn't help now! I'm not sure if it will be in the 2.2 release coming this year, or the 3.0 release next year.

Not to derail this PR by going too far off-topic, but instead of dropping `net451` you'll probably want to bump it to `net461` instead, and also have `netstandard2.0`. The current guidance to avoid weird binding redirect problems is to have both.

**Comment by kjnilsson** [comment]
I'm happy to consider bumping minimum version to `net461` for v6.0 unless there are any major objections.

**Comment by michaelklishin** [comment]
According to Wikipedia .NET 4.6.1 was [released in November 2015](https://en.wikipedia.org/wiki/.NET_Framework_version_history#.NET_Framework_4.6.1). I don't think it's too aggressive to require it for 6.0.

**Comment by bording** [comment]
The NServiceBus RabbitMQ transport still supports `net452`, but at this point, I'm happy to have a reason to force an update on that. 6.0 being `net461` minimum works for me.

**Comment by paulomorgado** [comment]
Seems related to https://github.com/dotnet/sourcelink/issues/179

This is related to the build tools, not the targets of the library.

.NET Framework 4.5.1 is no longer supported, but .NET Framework 4.5.2 is: https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework

Why is this being built a non-Windows operating system?

**Comment by michaelklishin** [comment]
@paulomorgado because Windows is still far from the industry standard for automation friendliness and .NET Core is supposedly cross platform.

**Comment by michaelklishin** [comment]
We are not going to move this client's CI to Windows (at least not yet) and not interested in debating the state of Windows automation (our team has to support Windows and Windows users beyond this client and we know first hand what it's like).

**Comment by paulomorgado** [comment]
My intention was only to know why. If it was only for test purposes, I could remove source linking from non-Windows CIs.

I think I can work around this. I'll see if I can tackle it over the weekend.

**Comment by bording** [comment]
I believe the binaries they ship are built from their Linux CI, so there isn’t much point in excluding SourceLink.

I think this PR is going to have to wait until LibGit2Sharp works properly on mono, which is something I’m investigating since I contribute to that project.

**Comment by paulomorgado** [comment]
The [original SourceLink implementation](https://github.com/ctaggart/SourceLink) used `git` commands. I'm pretty sure I can use them to work around this.

**Comment by niwrA** [comment]
Is there anything left that prevents this from being merged?

**Comment by bording** [comment]
At this point it's outdated, and should be replaced by the Microsoft Source Link packages.

**Comment by michaelklishin** [comment]
Sorry, this slipped under the radar in the 3.8 release rush. Let's do what @bording suggests, perhaps in a new PR that will be more visible? (I can help with that)

**Comment by lukebakken** [comment]
Closing this in favor of this method: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink
